---
    - name: Atualizar o sistema operacional
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar pré-requisitos do Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      become: true

    - name: Instalar docker
      apt:
        name: docker-ce
        state: latest
      become: true

    - name: Instalar Docker Compose
      get_url:  
        url: "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-{{ ansible_system | lower }}-{{ ansible_userspace_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      become: true

    - name: Iniciar e habilitar o serviço Docker
      systemd:
        name: docker
        state: started
        enabled: yes
      become: true
    
    - name: Clonar repositório do projeto
      git:
        repo: git@github.com:refinancy/refinancy-be.git
        dest: /tmp/refinancy-app
        version: HEAD
      become: true
    
    - name: Executar o docker-compose
      command: docker-compose -f /tmp/refinancy-app/docker-compose.yml up -d
      become: true
